packages:
  - '.'
verifyDepsBeforeRun: false
overrides:
  deepmerge-ts: 8.0.0
  effect: 3.20.0
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  prisma: true
